// 小學二年級上學期（小二上）
(function(){
  window.CNKEYS_DATASETS = window.CNKEYS_DATASETS || {};
  window.CNKEYS_DATASETS.g2s1 = {
  "grade": "小學二年級上學期",
  "gradeCode": "小二上",
  "lessons": [
    {
      "id": "L01",
      "lessonNo": 1,
      "title": "第1課",
      "words": [
        {
          "字": "呼",
          "注音": "ㄏㄨ",
          "id": "2-1-01-01",
          "char": "呼",
          "zhuyin": "ㄏㄨ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "白",
          "注音": "ㄅㄞˊ",
          "id": "2-1-01-02",
          "char": "白",
          "zhuyin": "ㄅㄞˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "雲",
          "注音": "ㄩㄣˊ",
          "id": "2-1-01-03",
          "char": "雲",
          "zhuyin": "ㄩㄣˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "柔",
          "注音": "ㄖㄡˊ",
          "id": "2-1-01-04",
          "char": "柔",
          "zhuyin": "ㄖㄡˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "前",
          "注音": "ㄑㄧㄢˊ",
          "id": "2-1-01-05",
          "char": "前",
          "zhuyin": "ㄑㄧㄢˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "游",
          "注音": "ㄧㄡˊ",
          "id": "2-1-01-06",
          "char": "游",
          "zhuyin": "ㄧㄡˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "噴",
          "注音": "ㄆㄣ",
          "id": "2-1-01-07",
          "char": "噴",
          "zhuyin": "ㄆㄣ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "美",
          "注音": "ㄇㄟˇ",
          "id": "2-1-01-08",
          "char": "美",
          "zhuyin": "ㄇㄟˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "麗",
          "注音": "ㄌㄧˋ",
          "id": "2-1-01-09",
          "char": "麗",
          "zhuyin": "ㄌㄧˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "柱",
          "注音": "ㄓㄨˋ",
          "id": "2-1-01-10",
          "char": "柱",
          "zhuyin": "ㄓㄨˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "試",
          "注音": "ㄕˋ",
          "id": "2-1-01-11",
          "char": "試",
          "zhuyin": "ㄕˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "吸",
          "注音": "ㄒㄧ",
          "id": "2-1-01-12",
          "char": "吸",
          "zhuyin": "ㄒㄧ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "用",
          "注音": "ㄩㄥˋ",
          "id": "2-1-01-13",
          "char": "用",
          "zhuyin": "ㄩㄥˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "力",
          "注音": "ㄌㄧˋ",
          "id": "2-1-01-14",
          "char": "力",
          "zhuyin": "ㄌㄧˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "哇",
          "注音": "ㄨㄚ",
          "id": "2-1-01-15",
          "char": "哇",
          "zhuyin": "ㄨㄚ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "又",
          "注音": "ㄧㄡˋ",
          "id": "2-1-01-16",
          "char": "又",
          "zhuyin": "ㄧㄡˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "第",
          "注音": "ㄉㄧˋ",
          "id": "2-1-01-17",
          "char": "第",
          "zhuyin": "ㄉㄧˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "功",
          "注音": "ㄍㄨㄥ",
          "id": "2-1-01-18",
          "char": "功",
          "zhuyin": "ㄍㄨㄥ",
          "grade": 2,
          "semester": 1,
          "lesson": 1,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L02",
      "lessonNo": 2,
      "title": "第2課",
      "words": [
        {
          "字": "爬",
          "注音": "ㄆㄚˊ",
          "id": "2-1-02-01",
          "char": "爬",
          "zhuyin": "ㄆㄚˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "梯",
          "注音": "ㄊㄧ",
          "id": "2-1-02-02",
          "char": "梯",
          "zhuyin": "ㄊㄧ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "紙",
          "注音": "ㄓˇ",
          "id": "2-1-02-03",
          "char": "紙",
          "zhuyin": "ㄓˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "條",
          "注音": "ㄊㄧㄠˊ",
          "id": "2-1-02-04",
          "char": "條",
          "zhuyin": "ㄊㄧㄠˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "線",
          "注音": "ㄒㄧㄢˋ",
          "id": "2-1-02-05",
          "char": "線",
          "zhuyin": "ㄒㄧㄢˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "像",
          "注音": "ㄒㄧㄤˋ",
          "id": "2-1-02-06",
          "char": "像",
          "zhuyin": "ㄒㄧㄤˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "身",
          "注音": "ㄕㄣ",
          "id": "2-1-02-07",
          "char": "身",
          "zhuyin": "ㄕㄣ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "生",
          "注音": "ㄕㄥ",
          "id": "2-1-02-08",
          "char": "生",
          "zhuyin": "ㄕㄥ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "迫",
          "注音": "ㄆㄛˋ",
          "id": "2-1-02-09",
          "char": "迫",
          "zhuyin": "ㄆㄛˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "及",
          "注音": "ㄐㄧˊ",
          "id": "2-1-02-10",
          "char": "及",
          "zhuyin": "ㄐㄧˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "待",
          "注音": "ㄉㄞˋ",
          "id": "2-1-02-11",
          "char": "待",
          "zhuyin": "ㄉㄞˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "站",
          "注音": "ㄓㄢˋ",
          "id": "2-1-02-12",
          "char": "站",
          "zhuyin": "ㄓㄢˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "沿",
          "注音": "ㄧㄢˊ",
          "id": "2-1-02-13",
          "char": "沿",
          "zhuyin": "ㄧㄢˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "頂",
          "注音": "ㄉㄧㄥˇ",
          "id": "2-1-02-14",
          "char": "頂",
          "zhuyin": "ㄉㄧㄥˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "格",
          "注音": "ㄍㄜˊ",
          "id": "2-1-02-15",
          "char": "格",
          "zhuyin": "ㄍㄜˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "哪",
          "注音": "ㄋㄚˇ",
          "id": "2-1-02-16",
          "char": "哪",
          "zhuyin": "ㄋㄚˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "才",
          "注音": "ㄘㄞˊ",
          "id": "2-1-02-17",
          "char": "才",
          "zhuyin": "ㄘㄞˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "最",
          "注音": "ㄗㄨㄟˋ",
          "id": "2-1-02-18",
          "char": "最",
          "zhuyin": "ㄗㄨㄟˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 2,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L03",
      "lessonNo": 3,
      "title": "第3課",
      "words": [
        {
          "字": "勇",
          "注音": "ㄩㄥˇ",
          "id": "2-1-03-01",
          "char": "勇",
          "zhuyin": "ㄩㄥˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "教",
          "注音": "ㄐㄧㄠˋ",
          "id": "2-1-03-02",
          "char": "教",
          "zhuyin": "ㄐㄧㄠˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "室",
          "注音": "ㄕˋ",
          "id": "2-1-03-03",
          "char": "室",
          "zhuyin": "ㄕˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "棵",
          "注音": "ㄎㄜ",
          "id": "2-1-03-04",
          "char": "棵",
          "zhuyin": "ㄎㄜ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "葉",
          "注音": "ㄧㄝˋ",
          "id": "2-1-03-05",
          "char": "葉",
          "zhuyin": "ㄧㄝˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "克",
          "注音": "ㄎㄜˋ",
          "id": "2-1-03-06",
          "char": "克",
          "zhuyin": "ㄎㄜˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "服",
          "注音": "ㄈㄨˊ",
          "id": "2-1-03-07",
          "char": "服",
          "zhuyin": "ㄈㄨˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "害",
          "注音": "ㄏㄞˋ",
          "id": "2-1-03-08",
          "char": "害",
          "zhuyin": "ㄏㄞˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "怕",
          "注音": "ㄆㄚˋ",
          "id": "2-1-03-09",
          "char": "怕",
          "zhuyin": "ㄆㄚˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "努",
          "注音": "ㄋㄨˇ",
          "id": "2-1-03-10",
          "char": "努",
          "zhuyin": "ㄋㄨˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "完",
          "注音": "ㄨㄢˊ",
          "id": "2-1-03-11",
          "char": "完",
          "zhuyin": "ㄨㄢˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "事",
          "注音": "ㄕˋ",
          "id": "2-1-03-12",
          "char": "事",
          "zhuyin": "ㄕˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "倒",
          "注音": "ㄉㄠˇ",
          "id": "2-1-03-13",
          "char": "倒",
          "zhuyin": "ㄉㄠˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "時",
          "注音": "ㄕˊ",
          "id": "2-1-03-14",
          "char": "時",
          "zhuyin": "ㄕˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "黑",
          "注音": "ㄏㄟ",
          "id": "2-1-03-15",
          "char": "黑",
          "zhuyin": "ㄏㄟ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "低",
          "注音": "ㄉㄧ",
          "id": "2-1-03-16",
          "char": "低",
          "zhuyin": "ㄉㄧ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "聲",
          "注音": "ㄕㄥ",
          "id": "2-1-03-17",
          "char": "聲",
          "zhuyin": "ㄕㄥ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "故",
          "注音": "ㄍㄨˋ",
          "id": "2-1-03-18",
          "char": "故",
          "zhuyin": "ㄍㄨˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 3,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L04",
      "lessonNo": 4,
      "title": "第4課",
      "words": [
        {
          "字": "塊",
          "注音": "ㄎㄨㄞˋ",
          "id": "2-1-04-01",
          "char": "塊",
          "zhuyin": "ㄎㄨㄞˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "圓",
          "注音": "ㄩㄢˊ",
          "id": "2-1-04-02",
          "char": "圓",
          "zhuyin": "ㄩㄢˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "形",
          "注音": "ㄒㄧㄥˊ",
          "id": "2-1-04-03",
          "char": "形",
          "zhuyin": "ㄒㄧㄥˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "芝",
          "注音": "ㄓ",
          "id": "2-1-04-04",
          "char": "芝",
          "zhuyin": "ㄓ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "麻",
          "注音": "ㄇㄚˊ",
          "id": "2-1-04-05",
          "char": "麻",
          "zhuyin": "ㄇㄚˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "餅",
          "注音": "ㄅㄧㄥˇ",
          "id": "2-1-04-06",
          "char": "餅",
          "zhuyin": "ㄅㄧㄥˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "咬",
          "注音": "ㄧㄠˇ",
          "id": "2-1-04-07",
          "char": "咬",
          "zhuyin": "ㄧㄠˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "飯",
          "注音": "ㄈㄢˋ",
          "id": "2-1-04-08",
          "char": "飯",
          "zhuyin": "ㄈㄢˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "做",
          "注音": "ㄗㄨㄛˋ",
          "id": "2-1-04-09",
          "char": "做",
          "zhuyin": "ㄗㄨㄛˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "課",
          "注音": "ㄎㄜˋ",
          "id": "2-1-04-10",
          "char": "課",
          "zhuyin": "ㄎㄜˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "洗",
          "注音": "ㄒㄧˇ",
          "id": "2-1-04-11",
          "char": "洗",
          "zhuyin": "ㄒㄧˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "澡",
          "注音": "ㄗㄠˇ",
          "id": "2-1-04-12",
          "char": "澡",
          "zhuyin": "ㄗㄠˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "拾",
          "注音": "ㄕˊ",
          "id": "2-1-04-13",
          "char": "拾",
          "zhuyin": "ㄕˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "整",
          "注音": "ㄓㄥˇ",
          "id": "2-1-04-14",
          "char": "整",
          "zhuyin": "ㄓㄥˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "包",
          "注音": "ㄅㄠ",
          "id": "2-1-04-15",
          "char": "包",
          "zhuyin": "ㄅㄠ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "遊",
          "注音": "ㄧㄡˊ",
          "id": "2-1-04-16",
          "char": "遊",
          "zhuyin": "ㄧㄡˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "戲",
          "注音": "ㄒㄧˋ",
          "id": "2-1-04-17",
          "char": "戲",
          "zhuyin": "ㄒㄧˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "剩",
          "注音": "ㄕㄥˋ",
          "id": "2-1-04-18",
          "char": "剩",
          "zhuyin": "ㄕㄥˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 4,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L05",
      "lessonNo": 5,
      "title": "第5課",
      "words": [
        {
          "字": "蟲",
          "注音": "ㄔㄨㄥˊ",
          "id": "2-1-05-01",
          "char": "蟲",
          "zhuyin": "ㄔㄨㄥˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "森",
          "注音": "ㄙㄣ",
          "id": "2-1-05-02",
          "char": "森",
          "zhuyin": "ㄙㄣ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "動",
          "注音": "ㄉㄨㄥˋ",
          "id": "2-1-05-03",
          "char": "動",
          "zhuyin": "ㄉㄨㄥˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "物",
          "注音": "ㄨˋ",
          "id": "2-1-05-04",
          "char": "物",
          "zhuyin": "ㄨˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "王",
          "注音": "ㄨㄤˊ",
          "id": "2-1-05-05",
          "char": "王",
          "zhuyin": "ㄨㄤˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "坐",
          "注音": "ㄗㄨㄛˋ",
          "id": "2-1-05-06",
          "char": "坐",
          "zhuyin": "ㄗㄨㄛˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "午",
          "注音": "ㄨˇ",
          "id": "2-1-05-07",
          "char": "午",
          "zhuyin": "ㄨˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "停",
          "注音": "ㄊㄧㄥˊ",
          "id": "2-1-05-08",
          "char": "停",
          "zhuyin": "ㄊㄧㄥˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "座",
          "注音": "ㄗㄨㄛˋ",
          "id": "2-1-05-09",
          "char": "座",
          "zhuyin": "ㄗㄨㄛˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "橋",
          "注音": "ㄑㄧㄠˊ",
          "id": "2-1-05-10",
          "char": "橋",
          "zhuyin": "ㄑㄧㄠˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "急",
          "注音": "ㄐㄧˊ",
          "id": "2-1-05-11",
          "char": "急",
          "zhuyin": "ㄐㄧˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "原",
          "注音": "ㄩㄢˊ",
          "id": "2-1-05-12",
          "char": "原",
          "zhuyin": "ㄩㄢˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "從",
          "注音": "ㄘㄨㄥˊ",
          "id": "2-1-05-13",
          "char": "從",
          "zhuyin": "ㄘㄨㄥˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "此",
          "注音": "ㄘˇ",
          "id": "2-1-05-14",
          "char": "此",
          "zhuyin": "ㄘˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "管",
          "注音": "ㄍㄨㄢˇ",
          "id": "2-1-05-15",
          "char": "管",
          "zhuyin": "ㄍㄨㄢˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "百",
          "注音": "ㄅㄞˇ",
          "id": "2-1-05-16",
          "char": "百",
          "zhuyin": "ㄅㄞˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "科",
          "注音": "ㄎㄜ",
          "id": "2-1-05-17",
          "char": "科",
          "zhuyin": "ㄎㄜ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "全",
          "注音": "ㄑㄩㄢˊ",
          "id": "2-1-05-18",
          "char": "全",
          "zhuyin": "ㄑㄩㄢˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 5,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L06",
      "lessonNo": 6,
      "title": "第6課",
      "words": [
        {
          "字": "自",
          "注音": "ㄗˋ",
          "id": "2-1-06-01",
          "char": "自",
          "zhuyin": "ㄗˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "己",
          "注音": "ㄐㄧˇ",
          "id": "2-1-06-02",
          "char": "己",
          "zhuyin": "ㄐㄧˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "沙",
          "注音": "ㄕㄚ",
          "id": "2-1-06-03",
          "char": "沙",
          "zhuyin": "ㄕㄚ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "撿",
          "注音": "ㄐㄧㄢˇ",
          "id": "2-1-06-04",
          "char": "撿",
          "zhuyin": "ㄐㄧㄢˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "垃",
          "注音": "ㄌㄚ",
          "id": "2-1-06-05",
          "char": "垃",
          "zhuyin": "ㄌㄚ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "圾",
          "注音": "ㄐㄧˊ",
          "id": "2-1-06-06",
          "char": "圾",
          "zhuyin": "ㄐㄧˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "眼",
          "注音": "ㄧㄢˇ",
          "id": "2-1-06-07",
          "char": "眼",
          "zhuyin": "ㄧㄢˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "膠",
          "注音": "ㄐㄧㄠ",
          "id": "2-1-06-08",
          "char": "膠",
          "zhuyin": "ㄐㄧㄠ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "對",
          "注音": "ㄉㄨㄟˋ",
          "id": "2-1-06-09",
          "char": "對",
          "zhuyin": "ㄉㄨㄟˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "牠",
          "注音": "ㄊㄚ",
          "id": "2-1-06-10",
          "char": "牠",
          "zhuyin": "ㄊㄚ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "安",
          "注音": "ㄢ",
          "id": "2-1-06-11",
          "char": "安",
          "zhuyin": "ㄢ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "吧",
          "注音": "ㄅㄚ",
          "id": "2-1-06-12",
          "char": "吧",
          "zhuyin": "ㄅㄚ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "如",
          "注音": "ㄖㄨˊ",
          "id": "2-1-06-13",
          "char": "如",
          "zhuyin": "ㄖㄨˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "該",
          "注音": "ㄍㄞ",
          "id": "2-1-06-14",
          "char": "該",
          "zhuyin": "ㄍㄞ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "留",
          "注音": "ㄌㄧㄡˊ",
          "id": "2-1-06-15",
          "char": "留",
          "zhuyin": "ㄌㄧㄡˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "便",
          "注音": "ㄅㄧㄢˋ",
          "id": "2-1-06-16",
          "char": "便",
          "zhuyin": "ㄅㄧㄢˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "減",
          "注音": "ㄐㄧㄢˇ",
          "id": "2-1-06-17",
          "char": "減",
          "zhuyin": "ㄐㄧㄢˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "少",
          "注音": "ㄕㄠˇ",
          "id": "2-1-06-18",
          "char": "少",
          "zhuyin": "ㄕㄠˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 6,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L07",
      "lessonNo": 7,
      "title": "第7課",
      "words": [
        {
          "字": "等",
          "注音": "ㄉㄥˇ",
          "id": "2-1-07-01",
          "char": "等",
          "zhuyin": "ㄉㄥˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "兔",
          "注音": "ㄊㄨˋ",
          "id": "2-1-07-02",
          "char": "兔",
          "zhuyin": "ㄊㄨˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "農",
          "注音": "ㄋㄨㄥˊ",
          "id": "2-1-07-03",
          "char": "農",
          "zhuyin": "ㄋㄨㄥˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "夫",
          "注音": "ㄈㄨ",
          "id": "2-1-07-04",
          "char": "夫",
          "zhuyin": "ㄈㄨ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "種",
          "注音": "ㄓㄨㄥˋ",
          "id": "2-1-07-05",
          "char": "種",
          "zhuyin": "ㄓㄨㄥˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "夏",
          "注音": "ㄒㄧㄚˋ",
          "id": "2-1-07-06",
          "char": "夏",
          "zhuyin": "ㄒㄧㄚˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "剛",
          "注音": "ㄍㄤ",
          "id": "2-1-07-07",
          "char": "剛",
          "zhuyin": "ㄍㄤ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "趕",
          "注音": "ㄍㄢˇ",
          "id": "2-1-07-08",
          "char": "趕",
          "zhuyin": "ㄍㄢˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "路",
          "注音": "ㄌㄨˋ",
          "id": "2-1-07-09",
          "char": "路",
          "zhuyin": "ㄌㄨˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "幸",
          "注音": "ㄒㄧㄥˋ",
          "id": "2-1-07-10",
          "char": "幸",
          "zhuyin": "ㄒㄧㄥˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "運",
          "注音": "ㄩㄣˋ",
          "id": "2-1-07-11",
          "char": "運",
          "zhuyin": "ㄩㄣˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "以",
          "注音": "ㄧˇ",
          "id": "2-1-07-12",
          "char": "以",
          "zhuyin": "ㄧˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "耕",
          "注音": "ㄍㄥ",
          "id": "2-1-07-13",
          "char": "耕",
          "zhuyin": "ㄍㄥ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "守",
          "注音": "ㄕㄡˇ",
          "id": "2-1-07-14",
          "char": "守",
          "zhuyin": "ㄕㄡˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "夜",
          "注音": "ㄧㄝˋ",
          "id": "2-1-07-15",
          "char": "夜",
          "zhuyin": "ㄧㄝˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "晚",
          "注音": "ㄨㄢˇ",
          "id": "2-1-07-16",
          "char": "晚",
          "zhuyin": "ㄨㄢˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "北",
          "注音": "ㄅㄟˇ",
          "id": "2-1-07-17",
          "char": "北",
          "zhuyin": "ㄅㄟˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "搖",
          "注音": "ㄧㄠˊ",
          "id": "2-1-07-18",
          "char": "搖",
          "zhuyin": "ㄧㄠˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 7,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L08",
      "lessonNo": 8,
      "title": "第8課",
      "words": [
        {
          "字": "角",
          "注音": "ㄐㄧㄠˇ",
          "id": "2-1-08-01",
          "char": "角",
          "zhuyin": "ㄐㄧㄠˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "腳",
          "注音": "ㄐㄧㄠˇ",
          "id": "2-1-08-02",
          "char": "腳",
          "zhuyin": "ㄐㄧㄠˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "渴",
          "注音": "ㄎㄜˇ",
          "id": "2-1-08-03",
          "char": "渴",
          "zhuyin": "ㄎㄜˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "鹿",
          "注音": "ㄌㄨˋ",
          "id": "2-1-08-04",
          "char": "鹿",
          "zhuyin": "ㄌㄨˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "喝",
          "注音": "ㄏㄜ",
          "id": "2-1-08-05",
          "char": "喝",
          "zhuyin": "ㄏㄜ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "影",
          "注音": "ㄧㄥˇ",
          "id": "2-1-08-06",
          "char": "影",
          "zhuyin": "ㄧㄥˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "意",
          "注音": "ㄧˋ",
          "id": "2-1-08-07",
          "char": "意",
          "zhuyin": "ㄧˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "卻",
          "注音": "ㄑㄩㄝˋ",
          "id": "2-1-08-08",
          "char": "卻",
          "zhuyin": "ㄑㄩㄝˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "獅",
          "注音": "ㄕ",
          "id": "2-1-08-09",
          "char": "獅",
          "zhuyin": "ㄕ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "追",
          "注音": "ㄓㄨㄟ",
          "id": "2-1-08-10",
          "char": "追",
          "zhuyin": "ㄓㄨㄟ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "被",
          "注音": "ㄅㄟˋ",
          "id": "2-1-08-11",
          "char": "被",
          "zhuyin": "ㄅㄟˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "枝",
          "注音": "ㄓ",
          "id": "2-1-08-12",
          "char": "枝",
          "zhuyin": "ㄓ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "掙",
          "注音": "ㄓㄥ",
          "id": "2-1-08-13",
          "char": "掙",
          "zhuyin": "ㄓㄥ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "脫",
          "注音": "ㄊㄨㄛ",
          "id": "2-1-08-14",
          "char": "脫",
          "zhuyin": "ㄊㄨㄛ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "速",
          "注音": "ㄙㄨˋ",
          "id": "2-1-08-15",
          "char": "速",
          "zhuyin": "ㄙㄨˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "度",
          "注音": "ㄉㄨˋ",
          "id": "2-1-08-16",
          "char": "度",
          "zhuyin": "ㄉㄨˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "直",
          "注音": "ㄓˊ",
          "id": "2-1-08-17",
          "char": "直",
          "zhuyin": "ㄓˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "救",
          "注音": "ㄐㄧㄡˋ",
          "id": "2-1-08-18",
          "char": "救",
          "zhuyin": "ㄐㄧㄡˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 8,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L09",
      "lessonNo": 9,
      "title": "第9課",
      "words": [
        {
          "字": "赤",
          "注音": "ㄔˋ",
          "id": "2-1-09-01",
          "char": "赤",
          "zhuyin": "ㄔˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "國",
          "注音": "ㄍㄨㄛˊ",
          "id": "2-1-09-02",
          "char": "國",
          "zhuyin": "ㄍㄨㄛˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "熱",
          "注音": "ㄖㄜˋ",
          "id": "2-1-09-03",
          "char": "熱",
          "zhuyin": "ㄖㄜˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "宮",
          "注音": "ㄍㄨㄥ",
          "id": "2-1-09-04",
          "char": "宮",
          "zhuyin": "ㄍㄨㄥ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "涼",
          "注音": "ㄌㄧㄤˊ",
          "id": "2-1-09-05",
          "char": "涼",
          "zhuyin": "ㄌㄧㄤˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "踩",
          "注音": "ㄘㄞˇ",
          "id": "2-1-09-06",
          "char": "踩",
          "zhuyin": "ㄘㄞˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "毯",
          "注音": "ㄊㄢˇ",
          "id": "2-1-09-07",
          "char": "毯",
          "zhuyin": "ㄊㄢˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "暖",
          "注音": "ㄋㄨㄢˇ",
          "id": "2-1-09-08",
          "char": "暖",
          "zhuyin": "ㄋㄨㄢˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "馬",
          "注音": "ㄇㄚˇ",
          "id": "2-1-09-09",
          "char": "馬",
          "zhuyin": "ㄇㄚˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "壞",
          "注音": "ㄏㄨㄞˋ",
          "id": "2-1-09-10",
          "char": "壞",
          "zhuyin": "ㄏㄨㄞˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "難",
          "注音": "ㄋㄢˊ",
          "id": "2-1-09-11",
          "char": "難",
          "zhuyin": "ㄋㄢˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "定",
          "注音": "ㄉㄧㄥˋ",
          "id": "2-1-09-12",
          "char": "定",
          "zhuyin": "ㄉㄧㄥˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "更",
          "注音": "ㄍㄥˋ",
          "id": "2-1-09-13",
          "char": "更",
          "zhuyin": "ㄍㄥˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "隨",
          "注音": "ㄙㄨㄟˊ",
          "id": "2-1-09-14",
          "char": "隨",
          "zhuyin": "ㄙㄨㄟˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "主",
          "注音": "ㄓㄨˇ",
          "id": "2-1-09-15",
          "char": "主",
          "zhuyin": "ㄓㄨˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "法",
          "注音": "ㄈㄚˇ",
          "id": "2-1-09-16",
          "char": "法",
          "zhuyin": "ㄈㄚˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "於",
          "注音": "ㄩˊ",
          "id": "2-1-09-17",
          "char": "於",
          "zhuyin": "ㄩˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "舒",
          "注音": "ㄕㄨ",
          "id": "2-1-09-18",
          "char": "舒",
          "zhuyin": "ㄕㄨ",
          "grade": 2,
          "semester": 1,
          "lesson": 9,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L10",
      "lessonNo": 10,
      "title": "第10課",
      "words": [
        {
          "字": "群",
          "注音": "ㄑㄩㄣˊ",
          "id": "2-1-10-01",
          "char": "群",
          "zhuyin": "ㄑㄩㄣˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "靜",
          "注音": "ㄐㄧㄥˋ",
          "id": "2-1-10-02",
          "char": "靜",
          "zhuyin": "ㄐㄧㄥˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "抬",
          "注音": "ㄊㄞˊ",
          "id": "2-1-10-03",
          "char": "抬",
          "zhuyin": "ㄊㄞˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "非",
          "注音": "ㄈㄟ",
          "id": "2-1-10-04",
          "char": "非",
          "zhuyin": "ㄈㄟ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "趣",
          "注音": "ㄑㄩˋ",
          "id": "2-1-10-05",
          "char": "趣",
          "zhuyin": "ㄑㄩˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "近",
          "注音": "ㄐㄧㄣˋ",
          "id": "2-1-10-06",
          "char": "近",
          "zhuyin": "ㄐㄧㄣˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "堆",
          "注音": "ㄉㄨㄟ",
          "id": "2-1-10-07",
          "char": "堆",
          "zhuyin": "ㄉㄨㄟ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "棉",
          "注音": "ㄇㄧㄢˊ",
          "id": "2-1-10-08",
          "char": "棉",
          "zhuyin": "ㄇㄧㄢˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "遠",
          "注音": "ㄩㄢˇ",
          "id": "2-1-10-09",
          "char": "遠",
          "zhuyin": "ㄩㄢˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "景",
          "注音": "ㄐㄧㄥˇ",
          "id": "2-1-10-10",
          "char": "景",
          "zhuyin": "ㄐㄧㄥˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "忽",
          "注音": "ㄏㄨ",
          "id": "2-1-10-11",
          "char": "忽",
          "zhuyin": "ㄏㄨ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "聽",
          "注音": "ㄊㄧㄥ",
          "id": "2-1-10-12",
          "char": "聽",
          "zhuyin": "ㄊㄧㄥ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "揮",
          "注音": "ㄏㄨㄟ",
          "id": "2-1-10-13",
          "char": "揮",
          "zhuyin": "ㄏㄨㄟ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "慢",
          "注音": "ㄇㄢˋ",
          "id": "2-1-10-14",
          "char": "慢",
          "zhuyin": "ㄇㄢˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "依",
          "注音": "ㄧ",
          "id": "2-1-10-15",
          "char": "依",
          "zhuyin": "ㄧ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "捨",
          "注音": "ㄕㄜˇ",
          "id": "2-1-10-16",
          "char": "捨",
          "zhuyin": "ㄕㄜˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "放",
          "注音": "ㄈㄤˋ",
          "id": "2-1-10-17",
          "char": "放",
          "zhuyin": "ㄈㄤˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "假",
          "注音": "ㄐㄧㄚˇ",
          "id": "2-1-10-18",
          "char": "假",
          "zhuyin": "ㄐㄧㄚˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 10,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L11",
      "lessonNo": 11,
      "title": "第11課",
      "words": [
        {
          "字": "湯",
          "注音": "ㄊㄤ",
          "id": "2-1-11-01",
          "char": "湯",
          "zhuyin": "ㄊㄤ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "今",
          "注音": "ㄐㄧㄣ",
          "id": "2-1-11-02",
          "char": "今",
          "zhuyin": "ㄐㄧㄣ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "至",
          "注音": "ㄓˋ",
          "id": "2-1-11-03",
          "char": "至",
          "zhuyin": "ㄓˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "妹",
          "注音": "ㄇㄟˋ",
          "id": "2-1-11-04",
          "char": "妹",
          "zhuyin": "ㄇㄟˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "升",
          "注音": "ㄕㄥ",
          "id": "2-1-11-05",
          "char": "升",
          "zhuyin": "ㄕㄥ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "陽",
          "注音": "ㄧㄤˊ",
          "id": "2-1-11-06",
          "char": "陽",
          "zhuyin": "ㄧㄤˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "因",
          "注音": "ㄧㄣ",
          "id": "2-1-11-07",
          "char": "因",
          "zhuyin": "ㄧㄣ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "期",
          "注音": "ㄑㄧˊ",
          "id": "2-1-11-08",
          "char": "期",
          "zhuyin": "ㄑㄧˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "盯",
          "注音": "ㄉㄧㄥ",
          "id": "2-1-11-09",
          "char": "盯",
          "zhuyin": "ㄉㄧㄥ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "米",
          "注音": "ㄇㄧˇ",
          "id": "2-1-11-10",
          "char": "米",
          "zhuyin": "ㄇㄧˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "團",
          "注音": "ㄊㄨㄢˊ",
          "id": "2-1-11-11",
          "char": "團",
          "zhuyin": "ㄊㄨㄢˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "粉",
          "注音": "ㄈㄣˇ",
          "id": "2-1-11-12",
          "char": "粉",
          "zhuyin": "ㄈㄣˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "南",
          "注音": "ㄋㄢˊ",
          "id": "2-1-11-13",
          "char": "南",
          "zhuyin": "ㄋㄢˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "黃",
          "注音": "ㄏㄨㄤˊ",
          "id": "2-1-11-14",
          "char": "黃",
          "zhuyin": "ㄏㄨㄤˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "真",
          "注音": "ㄓㄣ",
          "id": "2-1-11-15",
          "char": "真",
          "zhuyin": "ㄓㄣ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "呵",
          "注音": "ㄏㄜ",
          "id": "2-1-11-16",
          "char": "呵",
          "zhuyin": "ㄏㄜ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "接",
          "注音": "ㄐㄧㄝ",
          "id": "2-1-11-17",
          "char": "接",
          "zhuyin": "ㄐㄧㄝ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "牛",
          "注音": "ㄋㄧㄡˊ",
          "id": "2-1-11-18",
          "char": "牛",
          "zhuyin": "ㄋㄧㄡˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 11,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L12",
      "lessonNo": 12,
      "title": "第12課",
      "words": [
        {
          "字": "野",
          "注音": "ㄧㄝˇ",
          "id": "2-1-12-01",
          "char": "野",
          "zhuyin": "ㄧㄝˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "本",
          "注音": "ㄅㄣˇ",
          "id": "2-1-12-02",
          "char": "本",
          "zhuyin": "ㄅㄣˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "模",
          "注音": "ㄇㄛˊ",
          "id": "2-1-12-03",
          "char": "模",
          "zhuyin": "ㄇㄛˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "型",
          "注音": "ㄒㄧㄥˊ",
          "id": "2-1-12-04",
          "char": "型",
          "zhuyin": "ㄒㄧㄥˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "蜜",
          "注音": "ㄇㄧˋ",
          "id": "2-1-12-05",
          "char": "蜜",
          "zhuyin": "ㄇㄧˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "蜂",
          "注音": "ㄈㄥ",
          "id": "2-1-12-06",
          "char": "蜂",
          "zhuyin": "ㄈㄥ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "蝴",
          "注音": "ㄏㄨˊ",
          "id": "2-1-12-07",
          "char": "蝴",
          "zhuyin": "ㄏㄨˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "蝶",
          "注音": "ㄉㄧㄝˊ",
          "id": "2-1-12-08",
          "char": "蝶",
          "zhuyin": "ㄉㄧㄝˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "飛",
          "注音": "ㄈㄟ",
          "id": "2-1-12-09",
          "char": "飛",
          "zhuyin": "ㄈㄟ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "活",
          "注音": "ㄏㄨㄛˊ",
          "id": "2-1-12-10",
          "char": "活",
          "zhuyin": "ㄏㄨㄛˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "圖",
          "注音": "ㄊㄨˊ",
          "id": "2-1-12-11",
          "char": "圖",
          "zhuyin": "ㄊㄨˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "筆",
          "注音": "ㄅㄧˇ",
          "id": "2-1-12-12",
          "char": "筆",
          "zhuyin": "ㄅㄧˇ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "料",
          "注音": "ㄌㄧㄠˋ",
          "id": "2-1-12-13",
          "char": "料",
          "zhuyin": "ㄌㄧㄠˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "湖",
          "注音": "ㄏㄨˊ",
          "id": "2-1-12-14",
          "char": "湖",
          "zhuyin": "ㄏㄨˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "調",
          "注音": "ㄊㄧㄠˊ",
          "id": "2-1-12-15",
          "char": "調",
          "zhuyin": "ㄊㄧㄠˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "迷",
          "注音": "ㄇㄧˊ",
          "id": "2-1-12-16",
          "char": "迷",
          "zhuyin": "ㄇㄧˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "逛",
          "注音": "ㄍㄨㄤˋ",
          "id": "2-1-12-17",
          "char": "逛",
          "zhuyin": "ㄍㄨㄤˋ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "兒",
          "注音": "ㄦˊ",
          "id": "2-1-12-18",
          "char": "兒",
          "zhuyin": "ㄦˊ",
          "grade": 2,
          "semester": 1,
          "lesson": 12,
          "term": "小二上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    }
  ]
};
})();
