// 小學二年級下學期（小二下）
(function(){
  window.CNKEYS_DATASETS = window.CNKEYS_DATASETS || {};
  window.CNKEYS_DATASETS.g2s2 = {
  "grade": "小學二年級下學期",
  "gradeCode": "小二下",
  "lessons": [
    {
      "id": "L01",
      "lessonNo": 1,
      "title": "第1課",
      "words": [
        {
          "字": "情",
          "注音": "ㄑㄧㄥˊ",
          "id": "2-2-01-01",
          "char": "情",
          "zhuyin": "ㄑㄧㄥˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "候",
          "注音": "ㄏㄡˋ",
          "id": "2-2-01-02",
          "char": "候",
          "zhuyin": "ㄏㄡˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "翠",
          "注音": "ㄘㄨㄟˋ",
          "id": "2-2-01-03",
          "char": "翠",
          "zhuyin": "ㄘㄨㄟˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "溜",
          "注音": "ㄌㄧㄡ",
          "id": "2-2-01-04",
          "char": "溜",
          "zhuyin": "ㄌㄧㄡ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "滑",
          "注音": "ㄏㄨㄚˊ",
          "id": "2-2-01-05",
          "char": "滑",
          "zhuyin": "ㄏㄨㄚˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "傳",
          "注音": "ㄔㄨㄢˊ",
          "id": "2-2-01-06",
          "char": "傳",
          "zhuyin": "ㄔㄨㄢˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "深",
          "注音": "ㄕㄣ",
          "id": "2-2-01-07",
          "char": "深",
          "zhuyin": "ㄕㄣ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "泳",
          "注音": "ㄩㄥˇ",
          "id": "2-2-01-08",
          "char": "泳",
          "zhuyin": "ㄩㄥˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "淚",
          "注音": "ㄌㄟˋ",
          "id": "2-2-01-09",
          "char": "淚",
          "zhuyin": "ㄌㄟˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "火",
          "注音": "ㄏㄨㄛˇ",
          "id": "2-2-01-10",
          "char": "火",
          "zhuyin": "ㄏㄨㄛˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "奔",
          "注音": "ㄅㄣ",
          "id": "2-2-01-11",
          "char": "奔",
          "zhuyin": "ㄅㄣ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "怒",
          "注音": "ㄋㄨˋ",
          "id": "2-2-01-12",
          "char": "怒",
          "zhuyin": "ㄋㄨˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "拋",
          "注音": "ㄆㄠ",
          "id": "2-2-01-13",
          "char": "拋",
          "zhuyin": "ㄆㄠ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "潔",
          "注音": "ㄐㄧㄝˊ",
          "id": "2-2-01-14",
          "char": "潔",
          "zhuyin": "ㄐㄧㄝˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "舞",
          "注音": "ㄨˇ",
          "id": "2-2-01-15",
          "char": "舞",
          "zhuyin": "ㄨˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "各",
          "注音": "ㄍㄜˋ",
          "id": "2-2-01-16",
          "char": "各",
          "zhuyin": "ㄍㄜˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "同",
          "注音": "ㄊㄨㄥˊ",
          "id": "2-2-01-17",
          "char": "同",
          "zhuyin": "ㄊㄨㄥˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "受",
          "注音": "ㄕㄡˋ",
          "id": "2-2-01-18",
          "char": "受",
          "zhuyin": "ㄕㄡˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 1,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L02",
      "lessonNo": 2,
      "title": "第2課",
      "words": [
        {
          "字": "敢",
          "注音": "ㄍㄢˇ",
          "id": "2-2-02-01",
          "char": "敢",
          "zhuyin": "ㄍㄢˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "超",
          "注音": "ㄔㄠ",
          "id": "2-2-02-02",
          "char": "超",
          "zhuyin": "ㄔㄠ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "弟",
          "注音": "ㄉㄧˋ",
          "id": "2-2-02-03",
          "char": "弟",
          "zhuyin": "ㄉㄧˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "院",
          "注音": "ㄩㄢˋ",
          "id": "2-2-02-04",
          "char": "院",
          "zhuyin": "ㄩㄢˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "正",
          "注音": "ㄓㄥˋ",
          "id": "2-2-02-05",
          "char": "正",
          "zhuyin": "ㄓㄥˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "破",
          "注音": "ㄆㄛˋ",
          "id": "2-2-02-06",
          "char": "破",
          "zhuyin": "ㄆㄛˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "所",
          "注音": "ㄙㄨㄛˇ",
          "id": "2-2-02-07",
          "char": "所",
          "zhuyin": "ㄙㄨㄛˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "伸",
          "注音": "ㄕㄣ",
          "id": "2-2-02-08",
          "char": "伸",
          "zhuyin": "ㄕㄣ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "點",
          "注音": "ㄉㄧㄢˇ",
          "id": "2-2-02-09",
          "char": "點",
          "zhuyin": "ㄉㄧㄢˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "重",
          "注音": "ㄓㄨㄥˋ",
          "id": "2-2-02-10",
          "char": "重",
          "zhuyin": "ㄓㄨㄥˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "石",
          "注音": "ㄕˊ",
          "id": "2-2-02-11",
          "char": "石",
          "zhuyin": "ㄕˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "消",
          "注音": "ㄒㄧㄠ",
          "id": "2-2-02-12",
          "char": "消",
          "zhuyin": "ㄒㄧㄠ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "失",
          "注音": "ㄕ",
          "id": "2-2-02-13",
          "char": "失",
          "zhuyin": "ㄕ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "合",
          "注音": "ㄏㄜˊ",
          "id": "2-2-02-14",
          "char": "合",
          "zhuyin": "ㄏㄜˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "掉",
          "注音": "ㄉ一ㄠˋ",
          "id": "2-2-02-15",
          "char": "掉",
          "zhuyin": "ㄉ一ㄠˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "乾",
          "注音": "ㄍㄢ",
          "id": "2-2-02-16",
          "char": "乾",
          "zhuyin": "ㄍㄢ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "淨",
          "注音": "ㄐㄧㄥˋ",
          "id": "2-2-02-17",
          "char": "淨",
          "zhuyin": "ㄐㄧㄥˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "哥",
          "注音": "ㄍㄜ",
          "id": "2-2-02-18",
          "char": "哥",
          "zhuyin": "ㄍㄜ",
          "grade": 2,
          "semester": 2,
          "lesson": 2,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L03",
      "lessonNo": 3,
      "title": "第3課",
      "words": [
        {
          "字": "綿",
          "注音": "ㄇㄧㄢˊ",
          "id": "2-2-03-01",
          "char": "綿",
          "zhuyin": "ㄇㄧㄢˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "已",
          "注音": "ㄧˇ",
          "id": "2-2-03-02",
          "char": "已",
          "zhuyin": "ㄧˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "經",
          "注音": "ㄐㄧㄥ",
          "id": "2-2-03-03",
          "char": "經",
          "zhuyin": "ㄐㄧㄥ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "輸",
          "注音": "ㄕㄨ",
          "id": "2-2-03-04",
          "char": "輸",
          "zhuyin": "ㄕㄨ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "鼓",
          "注音": "ㄍㄨˇ",
          "id": "2-2-03-05",
          "char": "鼓",
          "zhuyin": "ㄍㄨˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "取",
          "注音": "ㄑㄩˇ",
          "id": "2-2-03-06",
          "char": "取",
          "zhuyin": "ㄑㄩˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "越",
          "注音": "ㄩㄝˋ",
          "id": "2-2-03-07",
          "char": "越",
          "zhuyin": "ㄩㄝˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "竟",
          "注音": "ㄐㄧㄥˋ",
          "id": "2-2-03-08",
          "char": "竟",
          "zhuyin": "ㄐㄧㄥˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "飄",
          "注音": "ㄆㄧㄠ",
          "id": "2-2-03-09",
          "char": "飄",
          "zhuyin": "ㄆㄧㄠ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "抓",
          "注音": "ㄓㄨㄚ",
          "id": "2-2-03-10",
          "char": "抓",
          "zhuyin": "ㄓㄨㄚ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "啦",
          "注音": "ㄌㄚ",
          "id": "2-2-03-11",
          "char": "啦",
          "zhuyin": "ㄌㄚ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "喊",
          "注音": "ㄏㄢˇ",
          "id": "2-2-03-12",
          "char": "喊",
          "zhuyin": "ㄏㄢˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "踢",
          "注音": "ㄊ一",
          "id": "2-2-03-13",
          "char": "踢",
          "zhuyin": "ㄊ一",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "結",
          "注音": "ㄐㄧㄝˊ",
          "id": "2-2-03-14",
          "char": "結",
          "zhuyin": "ㄐㄧㄝˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "變",
          "注音": "ㄅㄧㄢˋ",
          "id": "2-2-03-15",
          "char": "變",
          "zhuyin": "ㄅㄧㄢˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "讓",
          "注音": "ㄖㄤˋ",
          "id": "2-2-03-16",
          "char": "讓",
          "zhuyin": "ㄖㄤˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "終",
          "注音": "ㄓㄨㄥ",
          "id": "2-2-03-17",
          "char": "終",
          "zhuyin": "ㄓㄨㄥ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "冷",
          "注音": "ㄌㄥˇ",
          "id": "2-2-03-18",
          "char": "冷",
          "zhuyin": "ㄌㄥˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 3,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L04",
      "lessonNo": 4,
      "title": "第4課",
      "words": [
        {
          "字": "珠",
          "注音": "ㄓㄨ",
          "id": "2-2-04-01",
          "char": "珠",
          "zhuyin": "ㄓㄨ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "微",
          "注音": "ㄨㄟˊ",
          "id": "2-2-04-02",
          "char": "微",
          "zhuyin": "ㄨㄟˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "醒",
          "注音": "ㄒㄧㄥˇ",
          "id": "2-2-04-03",
          "char": "醒",
          "zhuyin": "ㄒㄧㄥˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "甲",
          "注音": "ㄐㄧㄚˇ",
          "id": "2-2-04-04",
          "char": "甲",
          "zhuyin": "ㄐㄧㄚˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "飄",
          "注音": "ㄆㄧㄠ",
          "id": "2-2-04-05",
          "char": "飄",
          "zhuyin": "ㄆㄧㄠ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "腰",
          "注音": "ㄧㄠ",
          "id": "2-2-04-06",
          "char": "腰",
          "zhuyin": "ㄧㄠ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "香",
          "注音": "ㄒㄧㄤ",
          "id": "2-2-04-07",
          "char": "香",
          "zhuyin": "ㄒㄧㄤ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "掛",
          "注音": "ㄍㄨㄚˋ",
          "id": "2-2-04-08",
          "char": "掛",
          "zhuyin": "ㄍㄨㄚˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "閃",
          "注音": "ㄕㄢˇ",
          "id": "2-2-04-09",
          "char": "閃",
          "zhuyin": "ㄕㄢˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "晶",
          "注音": "ㄐㄧㄥ",
          "id": "2-2-04-10",
          "char": "晶",
          "zhuyin": "ㄐㄧㄥ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "串",
          "注音": "ㄔㄨㄢˋ",
          "id": "2-2-04-11",
          "char": "串",
          "zhuyin": "ㄔㄨㄢˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "項",
          "注音": "ㄒㄧㄤˋ",
          "id": "2-2-04-12",
          "char": "項",
          "zhuyin": "ㄒㄧㄤˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "鍊",
          "注音": "ㄌㄧㄢˋ",
          "id": "2-2-04-13",
          "char": "鍊",
          "zhuyin": "ㄌㄧㄢˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "仙",
          "注音": "ㄒㄧㄢ",
          "id": "2-2-04-14",
          "char": "仙",
          "zhuyin": "ㄒㄧㄢ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "禮",
          "注音": "ㄌㄧˇ",
          "id": "2-2-04-15",
          "char": "禮",
          "zhuyin": "ㄌㄧˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "探",
          "注音": "ㄊㄢˋ",
          "id": "2-2-04-16",
          "char": "探",
          "zhuyin": "ㄊㄢˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "幫",
          "注音": "ㄅㄤ",
          "id": "2-2-04-17",
          "char": "幫",
          "zhuyin": "ㄅㄤ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "姐",
          "注音": "ㄐㄧㄝˇ",
          "id": "2-2-04-18",
          "char": "姐",
          "zhuyin": "ㄐㄧㄝˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 4,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L05",
      "lessonNo": 5,
      "title": "第5課",
      "words": [
        {
          "字": "病",
          "注音": "ㄅㄧㄥˋ",
          "id": "2-2-05-01",
          "char": "病",
          "zhuyin": "ㄅㄧㄥˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "晴",
          "注音": "ㄑㄧㄥˊ",
          "id": "2-2-05-02",
          "char": "晴",
          "zhuyin": "ㄑㄧㄥˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "份",
          "注音": "ㄈㄣˋ",
          "id": "2-2-05-03",
          "char": "份",
          "zhuyin": "ㄈㄣˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "牽",
          "注音": "ㄑㄧㄢ",
          "id": "2-2-05-04",
          "char": "牽",
          "zhuyin": "ㄑㄧㄢ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "步",
          "注音": "ㄅㄨˋ",
          "id": "2-2-05-05",
          "char": "步",
          "zhuyin": "ㄅㄨˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "段",
          "注音": "ㄉㄨㄢˋ",
          "id": "2-2-05-06",
          "char": "段",
          "zhuyin": "ㄉㄨㄢˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "毛",
          "注音": "ㄇㄠˊ",
          "id": "2-2-05-07",
          "char": "毛",
          "zhuyin": "ㄇㄠˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "晃",
          "注音": "ㄏㄨㄤˇ",
          "id": "2-2-05-08",
          "char": "晃",
          "zhuyin": "ㄏㄨㄤˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "籃",
          "注音": "ㄌㄢˊ",
          "id": "2-2-05-09",
          "char": "籃",
          "zhuyin": "ㄌㄢˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "亭",
          "注音": "ㄊㄧㄥˊ",
          "id": "2-2-05-10",
          "char": "亭",
          "zhuyin": "ㄊㄧㄥˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "忍",
          "注音": "ㄖㄣˇ",
          "id": "2-2-05-11",
          "char": "忍",
          "zhuyin": "ㄖㄣˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "秘",
          "注音": "ㄇㄧˋ",
          "id": "2-2-05-12",
          "char": "秘",
          "zhuyin": "ㄇㄧˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "耳",
          "注音": "ㄦˇ",
          "id": "2-2-05-13",
          "char": "耳",
          "zhuyin": "ㄦˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "聞",
          "注音": "ㄨㄣˊ",
          "id": "2-2-05-14",
          "char": "聞",
          "zhuyin": "ㄨㄣˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "味",
          "注音": "ㄨㄟˋ",
          "id": "2-2-05-15",
          "char": "味",
          "zhuyin": "ㄨㄟˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "浪",
          "注音": "ㄌㄤˋ",
          "id": "2-2-05-16",
          "char": "浪",
          "zhuyin": "ㄌㄤˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "寶",
          "注音": "ㄅㄠˇ",
          "id": "2-2-05-17",
          "char": "寶",
          "zhuyin": "ㄅㄠˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "清",
          "注音": "ㄑㄧㄥ",
          "id": "2-2-05-18",
          "char": "清",
          "zhuyin": "ㄑㄧㄥ",
          "grade": 2,
          "semester": 2,
          "lesson": 5,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L06",
      "lessonNo": 6,
      "title": "第6課",
      "words": [
        {
          "字": "封",
          "注音": "ㄈㄥ",
          "id": "2-2-06-01",
          "char": "封",
          "zhuyin": "ㄈㄥ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "信",
          "注音": "ㄒㄧㄣˋ",
          "id": "2-2-06-02",
          "char": "信",
          "zhuyin": "ㄒㄧㄣˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "親",
          "注音": "ㄑㄧㄣ",
          "id": "2-2-06-03",
          "char": "親",
          "zhuyin": "ㄑㄧㄣ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "貴",
          "注音": "ㄍㄨㄟˋ",
          "id": "2-2-06-04",
          "char": "貴",
          "zhuyin": "ㄍㄨㄟˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "洋",
          "注音": "ㄧㄤˊ",
          "id": "2-2-06-05",
          "char": "洋",
          "zhuyin": "ㄧㄤˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "蝦",
          "注音": "ㄒㄧㄚ",
          "id": "2-2-06-06",
          "char": "蝦",
          "zhuyin": "ㄒㄧㄚ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "植",
          "注音": "ㄓˊ",
          "id": "2-2-06-07",
          "char": "植",
          "zhuyin": "ㄓˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "量",
          "注音": "ㄌㄧㄤˋ",
          "id": "2-2-06-08",
          "char": "量",
          "zhuyin": "ㄌㄧㄤˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "污",
          "注音": "ㄨ",
          "id": "2-2-06-09",
          "char": "污",
          "zhuyin": "ㄨ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "染",
          "注音": "ㄖㄢˇ",
          "id": "2-2-06-10",
          "char": "染",
          "zhuyin": "ㄖㄢˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "使",
          "注音": "ㄕˇ",
          "id": "2-2-06-11",
          "char": "使",
          "zhuyin": "ㄕˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "決",
          "注音": "ㄐㄩㄝˊ",
          "id": "2-2-06-12",
          "char": "決",
          "zhuyin": "ㄐㄩㄝˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "具",
          "注音": "ㄐㄩˋ",
          "id": "2-2-06-13",
          "char": "具",
          "zhuyin": "ㄐㄩˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "資",
          "注音": "ㄗ",
          "id": "2-2-06-14",
          "char": "資",
          "zhuyin": "ㄗ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "源",
          "注音": "ㄩㄢˊ",
          "id": "2-2-06-15",
          "char": "源",
          "zhuyin": "ㄩㄢˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "費",
          "注音": "ㄈㄟˋ",
          "id": "2-2-06-16",
          "char": "費",
          "zhuyin": "ㄈㄟˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "康",
          "注音": "ㄎㄤ",
          "id": "2-2-06-17",
          "char": "康",
          "zhuyin": "ㄎㄤ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "復",
          "注音": "ㄈㄨˋ",
          "id": "2-2-06-18",
          "char": "復",
          "zhuyin": "ㄈㄨˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 6,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L07",
      "lessonNo": 7,
      "title": "第7課",
      "words": [
        {
          "字": "傘",
          "注音": "ㄙㄢˇ",
          "id": "2-2-07-01",
          "char": "傘",
          "zhuyin": "ㄙㄢˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "烏",
          "注音": "ㄨ",
          "id": "2-2-07-02",
          "char": "烏",
          "zhuyin": "ㄨ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "暗",
          "注音": "ㄢˋ",
          "id": "2-2-07-03",
          "char": "暗",
          "zhuyin": "ㄢˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "爺",
          "注音": "ㄧㄝˊ",
          "id": "2-2-07-04",
          "char": "爺",
          "zhuyin": "ㄧㄝˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "字",
          "注音": "ㄗˋ",
          "id": "2-2-07-05",
          "char": "字",
          "zhuyin": "ㄗˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "謎",
          "注音": "ㄇㄧˊ",
          "id": "2-2-07-06",
          "char": "謎",
          "zhuyin": "ㄇㄧˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "語",
          "注音": "ㄩˇ",
          "id": "2-2-07-07",
          "char": "語",
          "zhuyin": "ㄩˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "屋",
          "注音": "ㄨ",
          "id": "2-2-07-08",
          "char": "屋",
          "zhuyin": "ㄨ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "拐",
          "注音": "ㄍㄨㄞˇ",
          "id": "2-2-07-09",
          "char": "拐",
          "zhuyin": "ㄍㄨㄞˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "杖",
          "注音": "ㄓㄤˋ",
          "id": "2-2-07-10",
          "char": "杖",
          "zhuyin": "ㄓㄤˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "滴",
          "注音": "ㄉㄧ",
          "id": "2-2-07-11",
          "char": "滴",
          "zhuyin": "ㄉㄧ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "答",
          "注音": "ㄉㄚˊ",
          "id": "2-2-07-12",
          "char": "答",
          "zhuyin": "ㄉㄚˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "叩",
          "注音": "ㄎㄡˋ",
          "id": "2-2-07-13",
          "char": "叩",
          "zhuyin": "ㄎㄡˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "嘻",
          "注音": "ㄒㄧ",
          "id": "2-2-07-14",
          "char": "嘻",
          "zhuyin": "ㄒㄧ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "哈",
          "注音": "ㄏㄚ",
          "id": "2-2-07-15",
          "char": "哈",
          "zhuyin": "ㄏㄚ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "落",
          "注音": "ㄌㄨㄛˋ",
          "id": "2-2-07-16",
          "char": "落",
          "zhuyin": "ㄌㄨㄛˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "街",
          "注音": "ㄐㄧㄝ",
          "id": "2-2-07-17",
          "char": "街",
          "zhuyin": "ㄐㄧㄝ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "案",
          "注音": "ㄢˋ",
          "id": "2-2-07-18",
          "char": "案",
          "zhuyin": "ㄢˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 7,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L08",
      "lessonNo": 8,
      "title": "第8課",
      "words": [
        {
          "字": "丁",
          "注音": "ㄉㄧㄥ",
          "id": "2-2-08-01",
          "char": "丁",
          "zhuyin": "ㄉㄧㄥ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "公",
          "注音": "ㄍㄨㄥ",
          "id": "2-2-08-02",
          "char": "公",
          "zhuyin": "ㄍㄨㄥ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "每",
          "注音": "ㄇㄟˇ",
          "id": "2-2-08-03",
          "char": "每",
          "zhuyin": "ㄇㄟˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "認",
          "注音": "ㄖㄣˋ",
          "id": "2-2-08-04",
          "char": "認",
          "zhuyin": "ㄖㄣˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "比",
          "注音": "ㄅㄧˇ",
          "id": "2-2-08-05",
          "char": "比",
          "zhuyin": "ㄅㄧˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "客",
          "注音": "ㄎㄜˋ",
          "id": "2-2-08-06",
          "char": "客",
          "zhuyin": "ㄎㄜˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "相",
          "注音": "ㄒㄧㄤ",
          "id": "2-2-08-07",
          "char": "相",
          "zhuyin": "ㄒㄧㄤ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "興",
          "注音": "ㄒㄧㄥˋ",
          "id": "2-2-08-08",
          "char": "興",
          "zhuyin": "ㄒㄧㄥˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "照",
          "注音": "ㄓㄠˋ",
          "id": "2-2-08-09",
          "char": "照",
          "zhuyin": "ㄓㄠˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "皮",
          "注音": "ㄆㄧˊ",
          "id": "2-2-08-10",
          "char": "皮",
          "zhuyin": "ㄆㄧˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "摘",
          "注音": "ㄓㄞ",
          "id": "2-2-08-11",
          "char": "摘",
          "zhuyin": "ㄓㄞ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "立",
          "注音": "ㄌㄧˋ",
          "id": "2-2-08-12",
          "char": "立",
          "zhuyin": "ㄌㄧˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "位",
          "注音": "ㄨㄟˋ",
          "id": "2-2-08-13",
          "char": "位",
          "zhuyin": "ㄨㄟˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "新",
          "注音": "ㄒㄧㄣ",
          "id": "2-2-08-14",
          "char": "新",
          "zhuyin": "ㄒㄧㄣ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "它",
          "注音": "ㄊㄚ",
          "id": "2-2-08-15",
          "char": "它",
          "zhuyin": "ㄊㄚ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "欣",
          "注音": "ㄒㄧㄣ",
          "id": "2-2-08-16",
          "char": "欣",
          "zhuyin": "ㄒㄧㄣ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "賞",
          "注音": "ㄕㄤˇ",
          "id": "2-2-08-17",
          "char": "賞",
          "zhuyin": "ㄕㄤˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "妙",
          "注音": "ㄇㄧㄠˋ",
          "id": "2-2-08-18",
          "char": "妙",
          "zhuyin": "ㄇㄧㄠˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 8,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L09",
      "lessonNo": 9,
      "title": "第9課",
      "words": [
        {
          "字": "排",
          "注音": "ㄆㄞˊ",
          "id": "2-2-09-01",
          "char": "排",
          "zhuyin": "ㄆㄞˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "介",
          "注音": "ㄐㄧㄝˋ",
          "id": "2-2-09-02",
          "char": "介",
          "zhuyin": "ㄐㄧㄝˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "紹",
          "注音": "ㄕㄠˋ",
          "id": "2-2-09-03",
          "char": "紹",
          "zhuyin": "ㄕㄠˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "其",
          "注音": "ㄑㄧˊ",
          "id": "2-2-09-04",
          "char": "其",
          "zhuyin": "ㄑㄧˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "賣",
          "注音": "ㄇㄞˋ",
          "id": "2-2-09-05",
          "char": "賣",
          "zhuyin": "ㄇㄞˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "帽",
          "注音": "ㄇㄠˋ",
          "id": "2-2-09-06",
          "char": "帽",
          "zhuyin": "ㄇㄠˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "蛋",
          "注音": "ㄉㄢˋ",
          "id": "2-2-09-07",
          "char": "蛋",
          "zhuyin": "ㄉㄢˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "糕",
          "注音": "ㄍㄠ",
          "id": "2-2-09-08",
          "char": "糕",
          "zhuyin": "ㄍㄠ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "扶",
          "注音": "ㄈㄨˊ",
          "id": "2-2-09-09",
          "char": "扶",
          "zhuyin": "ㄈㄨˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "買",
          "注音": "ㄇㄞˇ",
          "id": "2-2-09-10",
          "char": "買",
          "zhuyin": "ㄇㄞˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "休",
          "注音": "ㄒㄧㄡ",
          "id": "2-2-09-11",
          "char": "休",
          "zhuyin": "ㄒㄧㄡ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "息",
          "注音": "ㄒㄧˊ",
          "id": "2-2-09-12",
          "char": "息",
          "zhuyin": "ㄒㄧˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "拿",
          "注音": "ㄋㄚˊ",
          "id": "2-2-09-13",
          "char": "拿",
          "zhuyin": "ㄋㄚˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "精",
          "注音": "ㄐㄧㄥ",
          "id": "2-2-09-14",
          "char": "精",
          "zhuyin": "ㄐㄧㄥ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "采",
          "注音": "ㄘㄞˇ",
          "id": "2-2-09-15",
          "char": "采",
          "zhuyin": "ㄘㄞˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "希",
          "注音": "ㄒㄧ",
          "id": "2-2-09-16",
          "char": "希",
          "zhuyin": "ㄒㄧ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "望",
          "注音": "ㄨㄤˋ",
          "id": "2-2-09-17",
          "char": "望",
          "zhuyin": "ㄨㄤˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "讀",
          "注音": "ㄉㄨˊ",
          "id": "2-2-09-18",
          "char": "讀",
          "zhuyin": "ㄉㄨˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 9,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L10",
      "lessonNo": 10,
      "title": "第10課",
      "words": [
        {
          "字": "銀",
          "注音": "ㄧㄣˊ",
          "id": "2-2-10-01",
          "char": "銀",
          "zhuyin": "ㄧㄣˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "年",
          "注音": "ㄋㄧㄢˊ",
          "id": "2-2-10-02",
          "char": "年",
          "zhuyin": "ㄋㄧㄢˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "幼",
          "注音": "ㄧㄡˋ",
          "id": "2-2-10-03",
          "char": "幼",
          "zhuyin": "ㄧㄡˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "女",
          "注音": "ㄋㄩˇ",
          "id": "2-2-10-04",
          "char": "女",
          "zhuyin": "ㄋㄩˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "願",
          "注音": "ㄩㄢˋ",
          "id": "2-2-10-05",
          "char": "願",
          "zhuyin": "ㄩㄢˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "碰",
          "注音": "ㄆㄥˋ",
          "id": "2-2-10-06",
          "char": "碰",
          "zhuyin": "ㄆㄥˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "桌",
          "注音": "ㄓㄨㄛ",
          "id": "2-2-10-07",
          "char": "桌",
          "zhuyin": "ㄓㄨㄛ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "椅",
          "注音": "ㄧˇ",
          "id": "2-2-10-08",
          "char": "椅",
          "zhuyin": "ㄧˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "部",
          "注音": "ㄅㄨˋ",
          "id": "2-2-10-09",
          "char": "部",
          "zhuyin": "ㄅㄨˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "食",
          "注音": "ㄕˊ",
          "id": "2-2-10-10",
          "char": "食",
          "zhuyin": "ㄕˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "刻",
          "注音": "ㄎㄜˋ",
          "id": "2-2-10-11",
          "char": "刻",
          "zhuyin": "ㄎㄜˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "純",
          "注音": "ㄔㄨㄣˊ",
          "id": "2-2-10-12",
          "char": "純",
          "zhuyin": "ㄔㄨㄣˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "求",
          "注音": "ㄑㄧㄡˊ",
          "id": "2-2-10-13",
          "char": "求",
          "zhuyin": "ㄑㄧㄡˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "並",
          "注音": "ㄅㄧㄥˋ",
          "id": "2-2-10-14",
          "char": "並",
          "zhuyin": "ㄅㄧㄥˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "切",
          "注音": "ㄑㄧㄝ",
          "id": "2-2-10-15",
          "char": "切",
          "zhuyin": "ㄑㄧㄝ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "狀",
          "注音": "ㄓㄨㄤˋ",
          "id": "2-2-10-16",
          "char": "狀",
          "zhuyin": "ㄓㄨㄤˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "明",
          "注音": "ㄇㄧㄥˊ",
          "id": "2-2-10-17",
          "char": "明",
          "zhuyin": "ㄇㄧㄥˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "珍",
          "注音": "ㄓㄣ",
          "id": "2-2-10-18",
          "char": "珍",
          "zhuyin": "ㄓㄣ",
          "grade": 2,
          "semester": 2,
          "lesson": 10,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L11",
      "lessonNo": 11,
      "title": "第11課",
      "words": [
        {
          "字": "敗",
          "注音": "ㄅㄞˋ",
          "id": "2-2-11-01",
          "char": "敗",
          "zhuyin": "ㄅㄞˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "操",
          "注音": "ㄘㄠ",
          "id": "2-2-11-02",
          "char": "操",
          "zhuyin": "ㄘㄠ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "旁",
          "注音": "ㄆㄤˊ",
          "id": "2-2-11-03",
          "char": "旁",
          "zhuyin": "ㄆㄤˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "脖",
          "注音": "ㄅㄛˊ",
          "id": "2-2-11-04",
          "char": "脖",
          "zhuyin": "ㄅㄛˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "瞇",
          "注音": "ㄇㄧ",
          "id": "2-2-11-05",
          "char": "瞇",
          "zhuyin": "ㄇㄧ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "密",
          "注音": "ㄇㄧˋ",
          "id": "2-2-11-06",
          "char": "密",
          "zhuyin": "ㄇㄧˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "件",
          "注音": "ㄐㄧㄢˋ",
          "id": "2-2-11-07",
          "char": "件",
          "zhuyin": "ㄐㄧㄢˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "特",
          "注音": "ㄊㄜˋ",
          "id": "2-2-11-08",
          "char": "特",
          "zhuyin": "ㄊㄜˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "別",
          "注音": "ㄅㄧㄝˊ",
          "id": "2-2-11-09",
          "char": "別",
          "zhuyin": "ㄅㄧㄝˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "唱",
          "注音": "ㄔㄤˋ",
          "id": "2-2-11-10",
          "char": "唱",
          "zhuyin": "ㄔㄤˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "歌",
          "注音": "ㄍㄜ",
          "id": "2-2-11-11",
          "char": "歌",
          "zhuyin": "ㄍㄜ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "練",
          "注音": "ㄌㄧㄢˋ",
          "id": "2-2-11-12",
          "char": "練",
          "zhuyin": "ㄌㄧㄢˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "習",
          "注音": "ㄒㄧˊ",
          "id": "2-2-11-13",
          "char": "習",
          "zhuyin": "ㄒㄧˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "彈",
          "注音": "ㄊㄢˊ",
          "id": "2-2-11-14",
          "char": "彈",
          "zhuyin": "ㄊㄢˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "琴",
          "注音": "ㄑㄧㄣˊ",
          "id": "2-2-11-15",
          "char": "琴",
          "zhuyin": "ㄑㄧㄣˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "講",
          "注音": "ㄐㄧㄤˇ",
          "id": "2-2-11-16",
          "char": "講",
          "zhuyin": "ㄐㄧㄤˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "論",
          "注音": "ㄌㄨㄣˋ",
          "id": "2-2-11-17",
          "char": "論",
          "zhuyin": "ㄌㄨㄣˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "颳",
          "注音": "ㄍㄨㄚ",
          "id": "2-2-11-18",
          "char": "颳",
          "zhuyin": "ㄍㄨㄚ",
          "grade": 2,
          "semester": 2,
          "lesson": 11,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L12",
      "lessonNo": 12,
      "title": "第12課",
      "words": [
        {
          "字": "牆",
          "注音": "ㄑㄧㄤˊ",
          "id": "2-2-12-01",
          "char": "牆",
          "zhuyin": "ㄑㄧㄤˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "壁",
          "注音": "ㄅㄧˋ",
          "id": "2-2-12-02",
          "char": "壁",
          "zhuyin": "ㄅㄧˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "窗",
          "注音": "ㄔㄨㄤ",
          "id": "2-2-12-03",
          "char": "窗",
          "zhuyin": "ㄔㄨㄤ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "床",
          "注音": "ㄔㄨㄤˊ",
          "id": "2-2-12-04",
          "char": "床",
          "zhuyin": "ㄔㄨㄤˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "鋪",
          "注音": "ㄆㄨˋ",
          "id": "2-2-12-05",
          "char": "鋪",
          "zhuyin": "ㄆㄨˋ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "輪",
          "注音": "ㄌㄨㄣˊ",
          "id": "2-2-12-06",
          "char": "輪",
          "zhuyin": "ㄌㄨㄣˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "搬",
          "注音": "ㄅㄢ",
          "id": "2-2-12-07",
          "char": "搬",
          "zhuyin": "ㄅㄢ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "冰",
          "注音": "ㄅㄧㄥ",
          "id": "2-2-12-08",
          "char": "冰",
          "zhuyin": "ㄅㄧㄥ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "而",
          "注音": "ㄦˊ",
          "id": "2-2-12-09",
          "char": "而",
          "zhuyin": "ㄦˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "且",
          "注音": "ㄑㄧㄝˇ",
          "id": "2-2-12-10",
          "char": "且",
          "zhuyin": "ㄑㄧㄝˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "交",
          "注音": "ㄐㄧㄠ",
          "id": "2-2-12-11",
          "char": "交",
          "zhuyin": "ㄐㄧㄠ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "往",
          "注音": "ㄨㄤˇ",
          "id": "2-2-12-12",
          "char": "往",
          "zhuyin": "ㄨㄤˇ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "顆",
          "注音": "ㄎㄜ",
          "id": "2-2-12-13",
          "char": "顆",
          "zhuyin": "ㄎㄜ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "鮮",
          "注音": "ㄒㄧㄢ",
          "id": "2-2-12-14",
          "char": "鮮",
          "zhuyin": "ㄒㄧㄢ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "汁",
          "注音": "ㄓ",
          "id": "2-2-12-15",
          "char": "汁",
          "zhuyin": "ㄓ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "晨",
          "注音": "ㄔㄣˊ",
          "id": "2-2-12-16",
          "char": "晨",
          "zhuyin": "ㄔㄣˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "由",
          "注音": "ㄧㄡˊ",
          "id": "2-2-12-17",
          "char": "由",
          "zhuyin": "ㄧㄡˊ",
          "grade": 2,
          "semester": 2,
          "lesson": 12,
          "term": "小二下",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    }
  ]
};
})();
