// 小學三年級上學期（小三上）
(function(){
  window.CNKEYS_DATASETS = window.CNKEYS_DATASETS || {};
  window.CNKEYS_DATASETS.g3s1 = {
  "grade": "小學三年級上學期",
  "gradeCode": "小三上",
  "lessons": [
    {
      "id": "L01",
      "lessonNo": 1,
      "title": "第1課",
      "words": [
        {
          "字": "泥",
          "注音": "ㄋㄧˊ",
          "id": "3-1-01-01",
          "char": "泥",
          "zhuyin": "ㄋㄧˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "化",
          "注音": "ㄏㄨㄚˋ",
          "id": "3-1-01-02",
          "char": "化",
          "zhuyin": "ㄏㄨㄚˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "雀",
          "注音": "ㄑㄩㄝˋ",
          "id": "3-1-01-03",
          "char": "雀",
          "zhuyin": "ㄑㄩㄝˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "輕",
          "注音": "ㄑㄧㄥ",
          "id": "3-1-01-04",
          "char": "輕",
          "zhuyin": "ㄑㄧㄥ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "羽",
          "注音": "ㄩˇ",
          "id": "3-1-01-05",
          "char": "羽",
          "zhuyin": "ㄩˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "衣",
          "注音": "ㄧ",
          "id": "3-1-01-06",
          "char": "衣",
          "zhuyin": "ㄧ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "脆",
          "注音": "ㄘㄨㄟˋ",
          "id": "3-1-01-07",
          "char": "脆",
          "zhuyin": "ㄘㄨㄟˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "髮",
          "注音": "ㄈㄚˇ",
          "id": "3-1-01-08",
          "char": "髮",
          "zhuyin": "ㄈㄚˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "處",
          "注音": "ㄔㄨˋ",
          "id": "3-1-01-09",
          "char": "處",
          "zhuyin": "ㄔㄨˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "旅",
          "注音": "ㄌㄩˇ",
          "id": "3-1-01-10",
          "char": "旅",
          "zhuyin": "ㄌㄩˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "行",
          "注音": "ㄒㄧㄥˊ",
          "id": "3-1-01-11",
          "char": "行",
          "zhuyin": "ㄒㄧㄥˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "平",
          "注音": "ㄆㄧㄥˊ",
          "id": "3-1-01-12",
          "char": "平",
          "zhuyin": "ㄆㄧㄥˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "男",
          "注音": "ㄋㄢˊ",
          "id": "3-1-01-13",
          "char": "男",
          "zhuyin": "ㄋㄢˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "朗",
          "注音": "ㄌㄤˇ",
          "id": "3-1-01-14",
          "char": "朗",
          "zhuyin": "ㄌㄤˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "足",
          "注音": "ㄗㄨˊ",
          "id": "3-1-01-15",
          "char": "足",
          "zhuyin": "ㄗㄨˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 1,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L02",
      "lessonNo": 2,
      "title": "第2課",
      "words": [
        {
          "字": "訂",
          "注音": "ㄉㄧㄥˋ",
          "id": "3-1-02-01",
          "char": "訂",
          "zhuyin": "ㄉㄧㄥˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "記",
          "注音": "ㄐㄧˋ",
          "id": "3-1-02-02",
          "char": "記",
          "zhuyin": "ㄐㄧˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "言",
          "注音": "ㄧㄢˊ",
          "id": "3-1-02-03",
          "char": "言",
          "zhuyin": "ㄧㄢˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "持",
          "注音": "ㄔˊ",
          "id": "3-1-02-04",
          "char": "持",
          "zhuyin": "ㄔˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "提",
          "注音": "ㄊㄧˊ",
          "id": "3-1-02-05",
          "char": "提",
          "zhuyin": "ㄊㄧˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "級",
          "注音": "ㄐㄧˊ",
          "id": "3-1-02-06",
          "char": "級",
          "zhuyin": "ㄐㄧˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "約",
          "注音": "ㄩㄝ",
          "id": "3-1-02-07",
          "char": "約",
          "zhuyin": "ㄩㄝ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "紛",
          "注音": "ㄈㄣ",
          "id": "3-1-02-08",
          "char": "紛",
          "zhuyin": "ㄈㄣ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "廊",
          "注音": "ㄌㄤˊ",
          "id": "3-1-02-09",
          "char": "廊",
          "zhuyin": "ㄌㄤˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "班",
          "注音": "ㄅㄢ",
          "id": "3-1-02-10",
          "char": "班",
          "zhuyin": "ㄅㄢ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "錄",
          "注音": "ㄌㄨˋ",
          "id": "3-1-02-11",
          "char": "錄",
          "zhuyin": "ㄌㄨˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "聊",
          "注音": "ㄌㄧㄠˊ",
          "id": "3-1-02-12",
          "char": "聊",
          "zhuyin": "ㄌㄧㄠˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "烈",
          "注音": "ㄌㄧㄝˋ",
          "id": "3-1-02-13",
          "char": "烈",
          "zhuyin": "ㄌㄧㄝˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "些",
          "注音": "ㄒㄧㄝ",
          "id": "3-1-02-14",
          "char": "些",
          "zhuyin": "ㄒㄧㄝ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "愁",
          "注音": "ㄔㄡˊ",
          "id": "3-1-02-15",
          "char": "愁",
          "zhuyin": "ㄔㄡˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 2,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L03",
      "lessonNo": 3,
      "title": "第3課",
      "words": [
        {
          "字": "短",
          "注音": "ㄉㄨㄢˇ",
          "id": "3-1-03-01",
          "char": "短",
          "zhuyin": "ㄉㄨㄢˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "鐘",
          "注音": "ㄓㄨㄥ",
          "id": "3-1-03-02",
          "char": "鐘",
          "zhuyin": "ㄓㄨㄥ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "鬼",
          "注音": "ㄍㄨㄟˇ",
          "id": "3-1-03-03",
          "char": "鬼",
          "zhuyin": "ㄍㄨㄟˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "鬧",
          "注音": "ㄋㄠˋ",
          "id": "3-1-03-04",
          "char": "鬧",
          "zhuyin": "ㄋㄠˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "準",
          "注音": "ㄓㄨㄣˇ",
          "id": "3-1-03-05",
          "char": "準",
          "zhuyin": "ㄓㄨㄣˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "朝",
          "注音": "ㄓㄠ",
          "id": "3-1-03-06",
          "char": "朝",
          "zhuyin": "ㄓㄠ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "蹈",
          "注音": "ㄉㄠˋ",
          "id": "3-1-03-07",
          "char": "蹈",
          "zhuyin": "ㄉㄠˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "表",
          "注音": "ㄅㄧㄠˇ",
          "id": "3-1-03-08",
          "char": "表",
          "zhuyin": "ㄅㄧㄠˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "暢",
          "注音": "ㄔㄤˋ",
          "id": "3-1-03-09",
          "char": "暢",
          "zhuyin": "ㄔㄤˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "無",
          "注音": "ㄨˊ",
          "id": "3-1-03-10",
          "char": "無",
          "zhuyin": "ㄨˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "總",
          "注音": "ㄗㄨㄥˇ",
          "id": "3-1-03-11",
          "char": "總",
          "zhuyin": "ㄗㄨㄥˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "響",
          "注音": "ㄒㄧㄤˇ",
          "id": "3-1-03-12",
          "char": "響",
          "zhuyin": "ㄒㄧㄤˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "忘",
          "注音": "ㄨㄤˋ",
          "id": "3-1-03-13",
          "char": "忘",
          "zhuyin": "ㄨㄤˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "盡",
          "注音": "ㄐㄧㄣˋ",
          "id": "3-1-03-14",
          "char": "盡",
          "zhuyin": "ㄐㄧㄣˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "責",
          "注音": "ㄗㄜˊ",
          "id": "3-1-03-15",
          "char": "責",
          "zhuyin": "ㄗㄜˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 3,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L04",
      "lessonNo": 4,
      "title": "第4課",
      "words": [
        {
          "字": "指",
          "注音": "ㄓˇ",
          "id": "3-1-04-01",
          "char": "指",
          "zhuyin": "ㄓˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "夕",
          "注音": "ㄒㄧˋ",
          "id": "3-1-04-02",
          "char": "夕",
          "zhuyin": "ㄒㄧˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "賽",
          "注音": "ㄙㄞˋ",
          "id": "3-1-04-03",
          "char": "賽",
          "zhuyin": "ㄙㄞˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "緊",
          "注音": "ㄐㄧㄣˇ",
          "id": "3-1-04-04",
          "char": "緊",
          "zhuyin": "ㄐㄧㄣˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "店",
          "注音": "ㄉㄧㄢˋ",
          "id": "3-1-04-05",
          "char": "店",
          "zhuyin": "ㄉㄧㄢˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "逗",
          "注音": "ㄉㄡˋ",
          "id": "3-1-04-06",
          "char": "逗",
          "zhuyin": "ㄉㄡˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "轉",
          "注音": "ㄓㄨㄢˇ",
          "id": "3-1-04-07",
          "char": "轉",
          "zhuyin": "ㄓㄨㄢˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "露",
          "注音": "ㄌㄨˋ",
          "id": "3-1-04-08",
          "char": "露",
          "zhuyin": "ㄌㄨˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "業",
          "注音": "ㄧㄝˋ",
          "id": "3-1-04-09",
          "char": "業",
          "zhuyin": "ㄧㄝˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "專",
          "注音": "ㄓㄨㄢ",
          "id": "3-1-04-10",
          "char": "專",
          "zhuyin": "ㄓㄨㄢ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "勝",
          "注音": "ㄕㄥˋ",
          "id": "3-1-04-11",
          "char": "勝",
          "zhuyin": "ㄕㄥˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "利",
          "注音": "ㄌㄧˋ",
          "id": "3-1-04-12",
          "char": "利",
          "zhuyin": "ㄌㄧˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "悅",
          "注音": "ㄩㄝˋ",
          "id": "3-1-04-13",
          "char": "悅",
          "zhuyin": "ㄩㄝˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "乖",
          "注音": "ㄍㄨㄞ",
          "id": "3-1-04-14",
          "char": "乖",
          "zhuyin": "ㄍㄨㄞ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "溫",
          "注音": "ㄨㄣ",
          "id": "3-1-04-15",
          "char": "溫",
          "zhuyin": "ㄨㄣ",
          "grade": 3,
          "semester": 1,
          "lesson": 4,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L05",
      "lessonNo": 5,
      "title": "第5課",
      "words": [
        {
          "字": "沖",
          "注音": "ㄔㄨㄥ",
          "id": "3-1-05-01",
          "char": "沖",
          "zhuyin": "ㄔㄨㄥ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "注",
          "注音": "ㄓㄨˋ",
          "id": "3-1-05-02",
          "char": "注",
          "zhuyin": "ㄓㄨˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "吐",
          "注音": "ㄊㄨˇ",
          "id": "3-1-05-03",
          "char": "吐",
          "zhuyin": "ㄊㄨˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "員",
          "注音": "ㄩㄢˊ",
          "id": "3-1-05-04",
          "char": "員",
          "zhuyin": "ㄩㄢˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "龍",
          "注音": "ㄌㄨㄥˊ",
          "id": "3-1-05-05",
          "char": "龍",
          "zhuyin": "ㄌㄨㄥˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "警",
          "注音": "ㄐㄧㄥˇ",
          "id": "3-1-05-06",
          "char": "警",
          "zhuyin": "ㄐㄧㄥˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "諒",
          "注音": "ㄌ一ㄤˋ",
          "id": "3-1-05-07",
          "char": "諒",
          "zhuyin": "ㄌ一ㄤˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "菱",
          "注音": "ㄌ一ㄥˊ",
          "id": "3-1-05-08",
          "char": "菱",
          "zhuyin": "ㄌ一ㄥˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "兄",
          "注音": "ㄒㄩㄥ",
          "id": "3-1-05-09",
          "char": "兄",
          "zhuyin": "ㄒㄩㄥ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "歪",
          "注音": "ㄨㄞ",
          "id": "3-1-05-10",
          "char": "歪",
          "zhuyin": "ㄨㄞ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "防",
          "注音": "ㄈㄤˊ",
          "id": "3-1-05-11",
          "char": "防",
          "zhuyin": "ㄈㄤˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "鈴",
          "注音": "ㄌㄧㄥˊ",
          "id": "3-1-05-12",
          "char": "鈴",
          "zhuyin": "ㄌㄧㄥˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "傷",
          "注音": "ㄕㄤ",
          "id": "3-1-05-13",
          "char": "傷",
          "zhuyin": "ㄕㄤ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "死",
          "注音": "ㄙˇ",
          "id": "3-1-05-14",
          "char": "死",
          "zhuyin": "ㄙˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "脾",
          "注音": "ㄆㄧˊ",
          "id": "3-1-05-15",
          "char": "脾",
          "zhuyin": "ㄆㄧˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 5,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L06",
      "lessonNo": 6,
      "title": "第6課",
      "words": [
        {
          "字": "流",
          "注音": "ㄌㄧㄡˊ",
          "id": "3-1-06-01",
          "char": "流",
          "zhuyin": "ㄌㄧㄡˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "溼",
          "注音": "ㄕ",
          "id": "3-1-06-02",
          "char": "溼",
          "zhuyin": "ㄕ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "透",
          "注音": "ㄊㄡˋ",
          "id": "3-1-06-03",
          "char": "透",
          "zhuyin": "ㄊㄡˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "逃",
          "注音": "ㄊㄠˊ",
          "id": "3-1-06-04",
          "char": "逃",
          "zhuyin": "ㄊㄠˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "幕",
          "注音": "ㄇㄨˋ",
          "id": "3-1-06-05",
          "char": "幕",
          "zhuyin": "ㄇㄨˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "杯",
          "注音": "ㄅㄟ",
          "id": "3-1-06-06",
          "char": "杯",
          "zhuyin": "ㄅㄟ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "撞",
          "注音": "ㄓㄨㄤˋ",
          "id": "3-1-06-07",
          "char": "撞",
          "zhuyin": "ㄓㄨㄤˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "雙",
          "注音": "ㄕㄨㄤ",
          "id": "3-1-06-08",
          "char": "雙",
          "zhuyin": "ㄕㄨㄤ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "胸",
          "注音": "ㄒㄩㄥ",
          "id": "3-1-06-09",
          "char": "胸",
          "zhuyin": "ㄒㄩㄥ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "負",
          "注音": "ㄈㄨˋ",
          "id": "3-1-06-10",
          "char": "負",
          "zhuyin": "ㄈㄨˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "慌",
          "注音": "ㄏㄨㄤ",
          "id": "3-1-06-11",
          "char": "慌",
          "zhuyin": "ㄏㄨㄤ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "辦",
          "注音": "ㄅㄢˋ",
          "id": "3-1-06-12",
          "char": "辦",
          "zhuyin": "ㄅㄢˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "題",
          "注音": "ㄊㄧˊ",
          "id": "3-1-06-13",
          "char": "題",
          "zhuyin": "ㄊㄧˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "灰",
          "注音": "ㄏㄨㄟ",
          "id": "3-1-06-14",
          "char": "灰",
          "zhuyin": "ㄏㄨㄟ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "剪",
          "注音": "ㄐㄧㄢˇ",
          "id": "3-1-06-15",
          "char": "剪",
          "zhuyin": "ㄐㄧㄢˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 6,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L07",
      "lessonNo": 7,
      "title": "第7課",
      "words": [
        {
          "字": "藏",
          "注音": "ㄘㄤˊ",
          "id": "3-1-07-01",
          "char": "藏",
          "zhuyin": "ㄘㄤˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "藝",
          "注音": "ㄧˋ",
          "id": "3-1-07-02",
          "char": "藝",
          "zhuyin": "ㄧˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "捏",
          "注音": "ㄋ一ㄝ",
          "id": "3-1-07-03",
          "char": "捏",
          "zhuyin": "ㄋ一ㄝ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "摺",
          "注音": "ㄓㄜˊ",
          "id": "3-1-07-04",
          "char": "摺",
          "zhuyin": "ㄓㄜˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "背",
          "注音": "ㄅㄟˋ",
          "id": "3-1-07-05",
          "char": "背",
          "zhuyin": "ㄅㄟˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "斑",
          "注音": "ㄅㄢ",
          "id": "3-1-07-06",
          "char": "斑",
          "zhuyin": "ㄅㄢ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "皺",
          "注音": "ㄓㄡˋ",
          "id": "3-1-07-07",
          "char": "皺",
          "zhuyin": "ㄓㄡˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "懂",
          "注音": "ㄉㄨㄥˇ",
          "id": "3-1-07-08",
          "char": "懂",
          "zhuyin": "ㄉㄨㄥˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "凡",
          "注音": "ㄈㄢˊ",
          "id": "3-1-07-09",
          "char": "凡",
          "zhuyin": "ㄈㄢˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "梳",
          "注音": "ㄕㄨ",
          "id": "3-1-07-10",
          "char": "梳",
          "zhuyin": "ㄕㄨ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "夾",
          "注音": "ㄐㄧㄚˊ",
          "id": "3-1-07-11",
          "char": "夾",
          "zhuyin": "ㄐㄧㄚˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "仔",
          "注音": "ㄗㄞˇ",
          "id": "3-1-07-12",
          "char": "仔",
          "zhuyin": "ㄗㄞˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "術",
          "注音": "ㄕㄨˋ",
          "id": "3-1-07-13",
          "char": "術",
          "zhuyin": "ㄕㄨˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "雖",
          "注音": "ㄙㄨㄟ",
          "id": "3-1-07-14",
          "char": "雖",
          "zhuyin": "ㄙㄨㄟ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "創",
          "注音": "ㄔㄨㄤˋ",
          "id": "3-1-07-15",
          "char": "創",
          "zhuyin": "ㄔㄨㄤˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 7,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L08",
      "lessonNo": 8,
      "title": "第8課",
      "words": [
        {
          "字": "框",
          "注音": "ㄎㄨㄤ",
          "id": "3-1-08-01",
          "char": "框",
          "zhuyin": "ㄎㄨㄤ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "桶",
          "注音": "ㄊㄨㄥˇ",
          "id": "3-1-08-02",
          "char": "桶",
          "zhuyin": "ㄊㄨㄥˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "機",
          "注音": "ㄐㄧ",
          "id": "3-1-08-03",
          "char": "機",
          "zhuyin": "ㄐㄧ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "魔",
          "注音": "ㄇㄛˊ",
          "id": "3-1-08-04",
          "char": "魔",
          "zhuyin": "ㄇㄛˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "圍",
          "注音": "ㄨㄟˊ",
          "id": "3-1-08-05",
          "char": "圍",
          "zhuyin": "ㄨㄟˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "巾",
          "注音": "ㄐㄧㄣ",
          "id": "3-1-08-06",
          "char": "巾",
          "zhuyin": "ㄐㄧㄣ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "視",
          "注音": "ㄕˋ",
          "id": "3-1-08-07",
          "char": "視",
          "zhuyin": "ㄕˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "誤",
          "注音": "ㄨˋ",
          "id": "3-1-08-08",
          "char": "誤",
          "zhuyin": "ㄨˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "愉",
          "注音": "ㄩˊ",
          "id": "3-1-08-09",
          "char": "愉",
          "zhuyin": "ㄩˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "數",
          "注音": "ㄕㄨˋ",
          "id": "3-1-08-10",
          "char": "數",
          "zhuyin": "ㄕㄨˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "刀",
          "注音": "ㄉㄠ",
          "id": "3-1-08-11",
          "char": "刀",
          "zhuyin": "ㄉㄠ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "曾",
          "注音": "ㄘㄥˊ",
          "id": "3-1-08-12",
          "char": "曾",
          "zhuyin": "ㄘㄥˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "解",
          "注音": "ㄐㄧㄝˇ",
          "id": "3-1-08-13",
          "char": "解",
          "zhuyin": "ㄐㄧㄝˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "鏡",
          "注音": "ㄐㄧㄥˋ",
          "id": "3-1-08-14",
          "char": "鏡",
          "zhuyin": "ㄐㄧㄥˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "齊",
          "注音": "ㄑㄧˊ",
          "id": "3-1-08-15",
          "char": "齊",
          "zhuyin": "ㄑㄧˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 8,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L09",
      "lessonNo": 9,
      "title": "第9課",
      "words": [
        {
          "字": "蘋",
          "注音": "ㄆㄧㄥˊ",
          "id": "3-1-09-01",
          "char": "蘋",
          "zhuyin": "ㄆㄧㄥˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "藥",
          "注音": "ㄧㄠˋ",
          "id": "3-1-09-02",
          "char": "藥",
          "zhuyin": "ㄧㄠˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "醫",
          "注音": "ㄧ",
          "id": "3-1-09-03",
          "char": "醫",
          "zhuyin": "ㄧ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "穿",
          "注音": "ㄔㄨㄢ",
          "id": "3-1-09-04",
          "char": "穿",
          "zhuyin": "ㄔㄨㄢ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "袍",
          "注音": "ㄆㄠˊ",
          "id": "3-1-09-05",
          "char": "袍",
          "zhuyin": "ㄆㄠˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "戴",
          "注音": "ㄉㄞˋ",
          "id": "3-1-09-06",
          "char": "戴",
          "zhuyin": "ㄉㄞˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "筒",
          "注音": "ㄊㄨㄥˇ",
          "id": "3-1-09-07",
          "char": "筒",
          "zhuyin": "ㄊㄨㄥˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "啄",
          "注音": "ㄓㄨㄛˊ",
          "id": "3-1-09-08",
          "char": "啄",
          "zhuyin": "ㄓㄨㄛˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "備",
          "注音": "ㄅㄟˋ",
          "id": "3-1-09-09",
          "char": "備",
          "zhuyin": "ㄅㄟˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "幹",
          "注音": "ㄍㄢˋ",
          "id": "3-1-09-10",
          "char": "幹",
          "zhuyin": "ㄍㄢˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "敲",
          "注音": "ㄑ一ㄠ",
          "id": "3-1-09-11",
          "char": "敲",
          "zhuyin": "ㄑ一ㄠ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "毒",
          "注音": "ㄉㄨˊ",
          "id": "3-1-09-12",
          "char": "毒",
          "zhuyin": "ㄉㄨˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "體",
          "注音": "ㄊㄧˇ",
          "id": "3-1-09-13",
          "char": "體",
          "zhuyin": "ㄊㄧˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "淘",
          "注音": "ㄊㄠˊ",
          "id": "3-1-09-14",
          "char": "淘",
          "zhuyin": "ㄊㄠˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "般",
          "注音": "ㄅㄢ",
          "id": "3-1-09-15",
          "char": "般",
          "zhuyin": "ㄅㄢ",
          "grade": 3,
          "semester": 1,
          "lesson": 9,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L10",
      "lessonNo": 10,
      "title": "第10課",
      "words": [
        {
          "字": "極",
          "注音": "ㄐㄧˊ",
          "id": "3-1-10-01",
          "char": "極",
          "zhuyin": "ㄐㄧˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "根",
          "注音": "ㄍㄣ",
          "id": "3-1-10-02",
          "char": "根",
          "zhuyin": "ㄍㄣ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "腦",
          "注音": "ㄋㄠˇ",
          "id": "3-1-10-03",
          "char": "腦",
          "zhuyin": "ㄋㄠˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "膚",
          "注音": "ㄈㄨ",
          "id": "3-1-10-04",
          "char": "膚",
          "zhuyin": "ㄈㄨ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "熊",
          "注音": "ㄒㄩㄥˊ",
          "id": "3-1-10-05",
          "char": "熊",
          "zhuyin": "ㄒㄩㄥˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "豬",
          "注音": "ㄓㄨ",
          "id": "3-1-10-06",
          "char": "豬",
          "zhuyin": "ㄓㄨ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "象",
          "注音": "ㄒㄧㄤˋ",
          "id": "3-1-10-07",
          "char": "象",
          "zhuyin": "ㄒㄧㄤˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "雪",
          "注音": "ㄒㄩㄝˇ",
          "id": "3-1-10-08",
          "char": "雪",
          "zhuyin": "ㄒㄩㄝˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "實",
          "注音": "ㄕˊ",
          "id": "3-1-10-09",
          "char": "實",
          "zhuyin": "ㄕˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "反",
          "注音": "ㄈㄢˇ",
          "id": "3-1-10-10",
          "char": "反",
          "zhuyin": "ㄈㄢˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "射",
          "注音": "ㄕㄜˋ",
          "id": "3-1-10-11",
          "char": "射",
          "zhuyin": "ㄕㄜˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "呆",
          "注音": "ㄉㄞ",
          "id": "3-1-10-12",
          "char": "呆",
          "zhuyin": "ㄉㄞ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "印",
          "注音": "ㄧㄣˋ",
          "id": "3-1-10-13",
          "char": "印",
          "zhuyin": "ㄧㄣˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "憶",
          "注音": "ㄧˋ",
          "id": "3-1-10-14",
          "char": "憶",
          "zhuyin": "ㄧˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "滾",
          "注音": "ㄍㄨㄣˇ",
          "id": "3-1-10-15",
          "char": "滾",
          "zhuyin": "ㄍㄨㄣˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 10,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L11",
      "lessonNo": 11,
      "title": "第11課",
      "words": [
        {
          "字": "額",
          "注音": "ㄜˊ",
          "id": "3-1-11-01",
          "char": "額",
          "zhuyin": "ㄜˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "類",
          "注音": "ㄌㄟˋ",
          "id": "3-1-11-02",
          "char": "類",
          "zhuyin": "ㄌㄟˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "虎",
          "注音": "ㄏㄨˇ",
          "id": "3-1-11-03",
          "char": "虎",
          "zhuyin": "ㄏㄨˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "貓",
          "注音": "ㄇㄠ",
          "id": "3-1-11-04",
          "char": "貓",
          "zhuyin": "ㄇㄠ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "臺",
          "注音": "ㄊㄞˊ",
          "id": "3-1-11-05",
          "char": "臺",
          "zhuyin": "ㄊㄞˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "灣",
          "注音": "ㄨㄢ",
          "id": "3-1-11-06",
          "char": "灣",
          "zhuyin": "ㄨㄢ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "獨",
          "注音": "ㄉㄨˊ",
          "id": "3-1-11-07",
          "char": "獨",
          "zhuyin": "ㄉㄨˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "萬",
          "注音": "ㄨㄢˋ",
          "id": "3-1-11-08",
          "char": "萬",
          "zhuyin": "ㄨㄢˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "祖",
          "注音": "ㄗㄨˇ",
          "id": "3-1-11-09",
          "char": "祖",
          "zhuyin": "ㄗㄨˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "蛙",
          "注音": "ㄨㄚ",
          "id": "3-1-11-10",
          "char": "蛙",
          "zhuyin": "ㄨㄚ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "捉",
          "注音": "ㄓㄨㄛ",
          "id": "3-1-11-11",
          "char": "捉",
          "zhuyin": "ㄓㄨㄛ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "占",
          "注音": "ㄓㄢˋ",
          "id": "3-1-11-12",
          "char": "占",
          "zhuyin": "ㄓㄢˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "雞",
          "注音": "ㄐㄧ",
          "id": "3-1-11-13",
          "char": "雞",
          "zhuyin": "ㄐㄧ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "肉",
          "注音": "ㄖㄡˋ",
          "id": "3-1-11-14",
          "char": "肉",
          "zhuyin": "ㄖㄡˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "威",
          "注音": "ㄨㄟ",
          "id": "3-1-11-15",
          "char": "威",
          "zhuyin": "ㄨㄟ",
          "grade": 3,
          "semester": 1,
          "lesson": 11,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    },
    {
      "id": "L12",
      "lessonNo": 12,
      "title": "第12課",
      "words": [
        {
          "字": "攻",
          "注音": "ㄍㄨㄥ",
          "id": "3-1-12-01",
          "char": "攻",
          "zhuyin": "ㄍㄨㄥ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "敵",
          "注音": "ㄉㄧˊ",
          "id": "3-1-12-02",
          "char": "敵",
          "zhuyin": "ㄉㄧˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "擊",
          "注音": "ㄐㄧˊ",
          "id": "3-1-12-03",
          "char": "擊",
          "zhuyin": "ㄐㄧˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "技",
          "注音": "ㄐㄧˋ",
          "id": "3-1-12-04",
          "char": "技",
          "zhuyin": "ㄐㄧˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "昆",
          "注音": "ㄎㄨㄣ",
          "id": "3-1-12-05",
          "char": "昆",
          "zhuyin": "ㄎㄨㄣ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "命",
          "注音": "ㄇㄧㄥˋ",
          "id": "3-1-12-06",
          "char": "命",
          "zhuyin": "ㄇㄧㄥˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "周",
          "注音": "ㄓㄡ",
          "id": "3-1-12-07",
          "char": "周",
          "zhuyin": "ㄓㄡ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "竹",
          "注音": "ㄓㄨˊ",
          "id": "3-1-12-08",
          "char": "竹",
          "zhuyin": "ㄓㄨˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "節",
          "注音": "ㄐㄧㄝˊ",
          "id": "3-1-12-09",
          "char": "節",
          "zhuyin": "ㄐㄧㄝˊ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "演",
          "注音": "ㄧㄢˇ",
          "id": "3-1-12-10",
          "char": "演",
          "zhuyin": "ㄧㄢˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "逼",
          "注音": "ㄅㄧ",
          "id": "3-1-12-11",
          "char": "逼",
          "zhuyin": "ㄅㄧ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "退",
          "注音": "ㄊㄨㄟˋ",
          "id": "3-1-12-12",
          "char": "退",
          "zhuyin": "ㄊㄨㄟˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "保",
          "注音": "ㄅㄠˇ",
          "id": "3-1-12-13",
          "char": "保",
          "zhuyin": "ㄅㄠˇ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "翅",
          "注音": "ㄔˋ",
          "id": "3-1-12-14",
          "char": "翅",
          "zhuyin": "ㄔˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        },
        {
          "字": "屁",
          "注音": "ㄆ一ˋ",
          "id": "3-1-12-15",
          "char": "屁",
          "zhuyin": "ㄆ一ˋ",
          "grade": 3,
          "semester": 1,
          "lesson": 12,
          "term": "小三上",
          "words": [],
          "sentences": [],
          "radical": null,
          "strokes": null
        }
      ]
    }
  ]
};
})();
